### ISSUE TITLE
Windows10

### ISSUE THREAD

**Issue by prancius** [clean-docker/Magento2#30]
Would be nice to have clear instruction running for windows10
with docker, docket-compose and docker-sync . 
Command by command tutorial.
Now i am stuck that : Can not connect to docker at 127.0.0.1:2375

**Comment by CajuCLC** [comment]
You might want to use `export DOCKER_HOST=tcp://0.0.0.0:2375` on ~/.bash_profile and then you need to enable Expose Daemon on Docker settings.

**Comment by rafaelstz** [comment]
@prancius the suggestion above did work?

**Comment by CajuCLC** [comment]
Just adding some more context and making my comment easier to follow.
1. Enable **_Expose daemon on tcp://localhost:2375 without TLS_** on Docker settings.
2. Export DOCKER_HOST on WSL. You can do it two ways (I am doing option a).
a. `echo "export DOCKER_HOST=tcp://0.0.0.0:2375" >> ~/.bashrc && source ~/.bashrc`
`echo source ~/.bashrc >> ~/.bash_profile`

b. echo "export DOCKER_HOST=tcp://0.0.0.0:2375" >> ~/.bash_profile && source ~/.bash_profile`

First time I used option a, but with some new updates from Microsoft bashrc is not being sourced when it starts for some reason. That's why I added the source on .bash_profile. Either way will work for you.

**Comment by LiamKarlMitchell** [comment]
No curl on windows.

**Comment by CajuCLC** [comment]
@LiamKarlMitchell You don't need curl for this.
